# Generated by Django 3.2 on 2021-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('owner_phone_number', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('is_working', models.BooleanField()),
                ('image', models.ImageField(upload_to='imgs')),
            ],
        ),
    ]
