# Generated by Django 3.2 on 2021-04-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='owner_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
