# Generated by Django 3.2 on 2021-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_entries_owner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='owner_phone_number',
            field=models.BigIntegerField(),
        ),
    ]
